
kind: Service
apiVersion: v1
metadata:
  name: node-hello-world
  namespace: default
spec:
  selector:
    app: node-hello-world
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80

kind: Deployment
apiVersion: apps/v1beta1 # for versions before 1.9.0 use apps/v1beta2
metadata:
  name: node-hello-world
  namespace: default
spec:
  selector:
    matchLabels:
      app: node-hello-world
  replicas: 3 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: node-hello-world
    spec:
      containers:
      - name: node-hw
        image: r.cfcr.io/ericstoekl/ericstoekl/hello-world-node:master
        ports:
        - containerPort: 80
